spring:
  security:
    user:
      name: mfs
      roles: USER
    ignored: /metrics
  profiles:
    include: 'credentials'
server:
  port: 8090
logging.level.com.parcel.delivery: INFO
logging.level.root: INFO
management:
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
