spring:
  security:
    user:
      name: mfs
      roles: USER
    ignored: /metrics
server:
  port: 8090
logging.level.com.parcel: INFO
logging.level.root: INFO
logging.level.org.springframework: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS